In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

Ex2 จัดตำแหน่งให้ลำดับสุดท้ายมีค่าเป็นจำนวนเต็ม

In [10]:
np_matrix = np.random.rand(10,5)
index_choose = np.round(np_matrix[:,-1])
np_matrix[:,-1] = index_choose
np_matrix

array([[0.97154343, 0.99244109, 0.03833986, 0.24188668, 1.        ],
       [0.85853812, 0.40342603, 0.62330955, 0.9213131 , 0.        ],
       [0.48975132, 0.70040137, 0.52427036, 0.27896568, 0.        ],
       [0.58532626, 0.47744136, 0.85068472, 0.06059576, 1.        ],
       [0.70840914, 0.57104107, 0.86245926, 0.79482381, 1.        ],
       [0.63520023, 0.71106253, 0.24698017, 0.25851552, 1.        ],
       [0.04706545, 0.32853719, 0.02500029, 0.02084707, 0.        ],
       [0.92581985, 0.01988231, 0.41517659, 0.4514944 , 1.        ],
       [0.42130687, 0.11431142, 0.23980195, 0.31332907, 1.        ],
       [0.08501855, 0.52167463, 0.52687415, 0.58280211, 1.        ]])

In [19]:

np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 0, 2, 0, 2],
       [1, 2, 1, 1, 1],
       [0, 2, 2, 0, 0],
       [1, 1, 1, 2, 1],
       [0, 0, 0, 2, 0]])

Ex3 index จำนวนหลักเริ่มจาก 0,1,2,..n จึงต้องทำการปรับขนาดของ array หรือ index ให้เท่ากัน

In [20]:
idx = [0,1,2,3,4]
np_matrix[idx,:]

array([[0, 0, 2, 0, 2],
       [1, 2, 1, 1, 1],
       [0, 2, 2, 0, 0],
       [1, 1, 1, 2, 1],
       [0, 0, 0, 2, 0]])

Ex 4

In [23]:
np_matrix = np.random.randint(10,size=(10,5))
label_vector = np.random.randint(2,size=10)
np_matrix

array([[1, 6, 5, 0, 7],
       [9, 9, 4, 3, 1],
       [0, 6, 9, 3, 8],
       [3, 5, 9, 1, 3],
       [1, 1, 2, 1, 2],
       [4, 8, 9, 5, 1],
       [9, 9, 1, 2, 2],
       [3, 2, 8, 3, 2],
       [8, 5, 2, 7, 0],
       [5, 6, 7, 6, 6]])

In [24]:
label_vector

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

จัดกลุ่ม 0 เป็น train data

In [26]:
check = (label_vector == 0)
train_data = np_matrix[check]
train_data

array([[1, 6, 5, 0, 7],
       [9, 9, 4, 3, 1],
       [0, 6, 9, 3, 8],
       [4, 8, 9, 5, 1],
       [3, 2, 8, 3, 2],
       [5, 6, 7, 6, 6]])

จัดกลุ่ม 1 เป็น test data

In [27]:
check = (label_vector == 1)
test_data = np_matrix[check]
test_data

array([[3, 5, 9, 1, 3],
       [1, 1, 2, 1, 2],
       [9, 9, 1, 2, 2],
       [8, 5, 2, 7, 0]])

Ex.5 เรียงจากมากไปน้อย

In [28]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[1, 5, 1, 5, 5],
       [5, 5, 5, 4, 2],
       [2, 1, 4, 1, 1],
       [5, 2, 2, 1, 1],
       [1, 3, 2, 4, 2]])

In [30]:
np.sort(data[0,:])[::-1]

array([5, 5, 5, 1, 1])

Ex.6

In [32]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
np_test[(np_test%3==0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

Ex7 เปลี่ยน มุมเป็น 0

In [35]:
np_test[np.eye(5)==1] = 0
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])